name: sement_market_customer
description: Sement Market — Mijoz ilovasi.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  dio: ^5.4.0
  get_it: ^9.2.1
  go_router: ^17.1.0
  shared_preferences: ^2.2.2
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  intl: 0.20.2
  geolocator: ^14.0.2
  pusher_channels_flutter: ^2.2.1
  alice: ^1.0.0
  alice_dio: ^1.0.7
  smart_auth: ^3.2.0
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/
  generate: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/flutter_launcher_icon.png"
  adaptive_icon_background: "#F5BF1A"
  adaptive_icon_foreground: "assets/flutter_launcher_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff" # Orqa fon rangi (masalan, oq)
  image: assets/flutter_native_splash.png # Siz qo'ymoqchi bo'lgan rasm yo'li
  android_12:
    image: assets/flutter_native_splash.png # Android 12+ uchun rasm
    color: "#ffffff"